#!/usr/bin/env bash

CMAKEIFY_CHANNEL=$1
if [ "$CMAKEIFY_CHANNEL" == "" ]; then
  CMAKEIFY_CHANNEL=production
else
  echo Using $CMAKEIFY_CHANNEL channel
fi

if [ ! -d "cmakeify-downloads" ]; then 
  echo Creating cmakeify-downloads directory
  mkdir cmakeify-downloads
fi

curl -o cmakeify-downloads/cmakeify-run https://raw.githubusercontent.com/jomof/cmakeify-wrapper/master/cmakeify-$CMAKEIFY_CHANNEL &> cmakeify-downloads/download-cmakeify-run
chmod +x ./cmakeify-downloads/cmakeify-run
echo Customized cmakeify is trying to divert callee to local jar build/libs/cmakeify-${TRAVIS_TAG}.jar
./cmakeify-downloads/cmakeify-run build/libs/cmakeify-${TRAVIS_TAG}.jar $2 $3 $4 $5
