#!/usr/bin/env bash

CMAKEIFY_SCRIPT=https://raw.githubusercontent.com/jomof/cmakeify/master/cmakeify-production
CMAKEIFY_DOWNLOAD_FOLDER=.cmakeify/downloads

# Read any directives from .cmakeify.yml
eval $(cat .cmakeify.yml | grep "#directive" | sed -r 's/^.{11}/export /')

# Create the download folder
if [ ! -d "$CMAKEIFY_DOWNLOAD_FOLDER" ]; then
  mkdir -p $CMAKEIFY_DOWNLOAD_FOLDER
fi

echo Downloading CMAKEIFY_SCRIPT=$CMAKEIFY_SCRIPT to CMAKEIFY_SCRIPT=$CMAKEIFY_SCRIPT
curl -o $CMAKEIFY_DOWNLOAD_FOLDER/cmakeify-run $CMAKEIFY_SCRIPT &> $CMAKEIFY_DOWNLOAD_FOLDER/download-cmakeify-run.log
chmod +x $CMAKEIFY_DOWNLOAD_FOLDER/cmakeify-run
$CMAKEIFY_DOWNLOAD_FOLDER/cmakeify-run $@
