targets: [linux, android]
cmake:
  versions: [3.7.1, 3.7.2]
android:
  ndk:
    versions: [r13b, r14-beta1]
    compilers: [4.9, clang]
    platforms: [9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


